import PublicPageContainer from '../../components/containers/publicPageContainer';

export default function ConditionsDeUso() {
    return (
        <PublicPageContainer>
            <div className='max-w-7xl mr-auto ml-auto py-12 px-4'>
                <h1 className='text-3xl mb-2'>Condiciones de uso</h1>
                <br />
                <hr />
                <p>Te damos la bienvenida a Vendalia. Nos alegra mucho que estés aquí. Acomódate y diviértete, pero te pedimos que respetes las normas de la casa.</p>
                <br />
                <p>Esta política entró en vigor el 24 de julio de 2023.</p>
                <br />
                <p>Ten en cuenta que la sección 11 de las Condiciones contiene un Acuerdo de arbitraje vinculante y una renuncia a acciones colectivas para usuarios de América del Norte y del Sur. Al aceptar las Condiciones, tú y Vendalia aceptáis remitir cualesquiera disputas que surjan entre vosotros exclusivamente a arbitraje individual y no presentar una demanda ante los tribunales, excepto en las circunstancias limitadas descritas a continuación.</p>
                <br />
                <ol className='list-decimal ml-4 leading-8'>
                    <li>Aceptación de estas condiciones</li>
                    <li>Esos otros documentos que hemos mencionado</li>
                    <li>Tu privacidad</li>
                    <li>Tu cuenta de Vendalia</li>
                    <li>Tu Contenido</li>
                    <li>Tu uso de nuestros servicios</li>
                    <li>Rescisión</li>
                    <li>Garantías y limitación de responsabilidad (o las cosas por las que no nos puedes demandar)</li>
                    <li>Indemnización (y qué sucede si nos demandan por alguna acción tuya)</li>
                    <li>Disputas con otros usuarios</li>
                    <li>Acuerdo de arbitraje y resolución de disputas (América del Norte y del Sur)</li>
                    <li>Resolución de disputas (resto del mundo)</li>
                    <li>Cambios en las condiciones</li>
                    <li>Algunos puntos legales más matizados</li>
                    <li>Información de contacto</li>
                </ol>
                <br />
                <h2 className='text-2xl'>1. Aceptación de las presentes Condiciones</h2>
                <br />
                <p>Este documento y los demás documentos a los que hacemos referencia a continuación constituyen nuestras normas de la casa, o lo que llamamos oficialmente nuestras condiciones de uso (las &quot;Condiciones&quot;).</p>
                <br />
                <p>Las Condiciones son un contrato legalmente vinculante entre tú y Vendalia. Si vives en América del Norte o América del Sur, el contrato es entre tú y Vendalia, Inc.; si vives en cualquier otro lugar, el contrato es entre tú y Vendalia Ireland UC, una subsidiaria de Vendalia, Inc. Nos referiremos a ella simplemente como Vendalia, Inc. y a todas sus filiales conjuntamente como &quot;Vendalia&quot;.</p>
                <br />
                <p>Ten en cuenta que la sección 11 contiene una cláusula de arbitraje y de renuncia a acciones colectivas, aplicable a los usuarios de América del Norte y del Sur, y explica cómo renunciar al arbitraje. A menos que renuncies de forma válida, aceptas resolver cualesquiera disputas con Vendalia exclusivamente a través de un arbitraje específico vinculante, con excepciones limitadas únicamente. Esto significa que tú y Vendalia renunciáis al derecho a demandar ante los tribunales, al derecho a juicio con jurado o a participar en una acción colectiva o representativa. Lee esta sección detenidamente, ya que afecta a tus derechos.</p>
                <br />
                <p>Este contrato expone tus derechos y responsabilidades cuando usas Vendalia.com, Pattern by Vendalia, nuestras aplicaciones móviles y el resto de servicios que ofrece Vendalia (nos referiremos a todos estos elementos como nuestros &quot;Servicios&quot;), por lo que te pedimos que lo leas detenidamente. Al usar cualquiera de nuestros servicios (incluso navegar por uno de nuestros sitios web o aplicaciones), estás aceptando estas Condiciones. Si no estás de acuerdo con las Condiciones, no podrás usar nuestros Servicios. ¿Aceptas? ¡Estupendo, sigue leyendo!</p>
                <br />
                <h2 className='text-2xl'>2. Esos otros documentos que hemos mencionado</h2>
                <br />
                <p>Los Servicios de Vendalia conectan a la gente en todo el mundo, tanto en línea como localmente, para hacer, vender y comprar productos únicos. He aquí una guía práctica para ayudarte a entender las normas específicas que son relevantes para ti, en función de cómo utilices los Servicios:</p>

                <p>Las normas de la casa para todo el mundo. Si usas cualquiera de nuestros Servicios, aceptas estas Condiciones, nuestra política de privacidad y nuestra política contra la discriminación.</p>

                <p>Las normas de la casa para los vendedores. Si anuncias cualesquiera artículos para la venta a través de nuestros Servicios, estas políticas se aplican a tu persona. Puedes leerlas aquí.</p>

                <p>Las normas de la casa para los compradores. Si usas nuestros Servicios para navegar o comprar, estas políticas se aplican a tu persona. Puedes leerlas aquí.</p>

                <p>Las normas de la casa para terceros. Estas políticas se aplican a los propietarios de propiedad intelectual, los usuarios de la API de Vendalia, los afiliados y cualquiera que solicite información a Vendalia.</p>

                <p>Declaraciones sobre el posicionamiento en la búsqueda y la publicidad. En este documento se resume cómo organiza Vendalia los resultados de la búsqueda y los anuncios, entre los que se podría incluir Tu Contenido.</p>

                <p>Todas estas políticas son una parte de nuestras Condiciones, así que asegúrate de leer las que sean pertinentes para ti. Por supuesto, te interesará leer el resto de este documento, ya que se aplica a todo el mundo.</p>
                <br />
                <h2 className='text-2xl'>3. Tu privacidad</h2>
                <br />
                <p>Sabemos que tu información personal es importante para ti, así que es importante para nosotros. En nuestra política de privacidad se detalla cómo se recopila, utiliza y comparte tu información cuando usas nuestros Servicios. Al usar nuestros Servicios, también aceptas que podamos procesar tu información de las maneras que exponemos en la política de privacidad, por lo que te pedimos que la leas aquí.</p>

                <p>Tanto Vendalia como los vendedores de Vendalia procesan información personal de los miembros (por ejemplo, nombre del comprador, dirección de correo electrónico y dirección de envío) y, por tanto, se consideran controladores de datos independientes de la información personal de los compradores sujetos a la ley de la UE. Eso significa que cada parte es responsable de la información personal que procesa al proporcionar los Servicios. Por ejemplo, si un vendedor revela por accidente el nombre y la dirección de correo electrónico de un comprador al procesar el pedido de otro comprador de Vendalia, el responsable de dicha revelación no autorizada será el vendedor, no Vendalia.</p>

                <p>Si, no obstante, tú (como vendedor) y Vendalia sois considerados controladores de datos corresponsables de la información personal de los compradores, y si Vendalia es demandada, multada o incurriera de cualquier otro modo en gastos por una acción (o por omisión) tuya como controlador de datos corresponsable de la información personal del comprador, aceptas defender e indemnizar a Vendalia de conformidad con la sección 9 más abajo.</p>

                <br />
                <h2 className='text-2xl'>4. Tu cuenta de Vendalia</h2>
                <br />
                <p>Tendrás que crear una cuenta con Vendalia para utilizar algunos de nuestros Servicios. Estas son algunas normas acerca de las cuentas con Vendalia:</p>
                <br />
                <p><strong>A.</strong> Debes ser mayor de 18 años para utilizar nuestros Servicios. Los menores de entre 13 y 18 años solo pueden usar nuestros Servicios mediante una cuenta propiedad de uno de los padres o del tutor legal, con el permiso correspondiente y bajo su supervisión directa. No permitimos el uso de nuestros Servicios a niños menores de 13 años. Eres responsable de cualquier y toda actividad que un menor lleve a cabo en tu cuenta, y es probable que haya productos comerciales o servicios en línea a los que quieras limitar el acceso del menor. Para obtener más información, consulta la política de menores de edad.</p>
                <br />
                <p><strong>B.</strong> Sé honesto con nosotros. Facilita información fidedigna sobre ti. No es aceptable usar información falsa o hacerse pasar por otra persona o empresa a través de tu cuenta.</p>
                <br />
                <p><strong>C.</strong> Elige un nombre adecuado. Si decides no usar tu nombre completo como nombre asociado con tu cuenta, no podrás usar un lenguaje que sea ofensivo, vulgar ni que infrinja los derechos de propiedad intelectual de otra persona o que viole de cualquier otro modo las Condiciones.</p>
                <br />
                <p><strong>D.</strong> Eres responsable de tu cuenta. Eres la única persona responsable de toda la actividad de tu cuenta. Si vas a compartir la cuenta con otras personas, entonces la responsabilidad de toda la actividad recaerá en última instancia sobre la persona cuya información de facturación figure en la cuenta. Si te estás registrando como una entidad comercial, garantizas personalmente que tienes la autoridad para aceptar las Condiciones en nombre de la empresa. Normalmente no se pueden transferir las cuentas.</p>
                <br />
                <p><strong>E.</strong> Protege tu contraseña. Como hemos mencionado antes, eres la única persona responsable de toda la actividad de tu cuenta, por lo que es importante que protejas su contraseña. Aquí encontrarás un artículo de la Ayuda con información para reforzar la seguridad de tu cuenta.</p>
                <br />
                <p><strong>F.</strong> Seamos claros sobre nuestra relación. Las presentes condiciones no crean ninguna relación de agencia, asociación, joint venture, puesto de trabajo o franquicia entre tú y Vendalia.</p>
                <br />
                <p><strong>G.</strong> Casos y apelaciones. Para participar en nuestro sistema de casos (tal como se describe en la sección 10), o para apelar una acción de Vendalia, debes tener una cuenta.</p>
                <br />
                <p>Este detallado artículo de la Ayuda debería responder cualquier pregunta que tengas sobre el proceso para registrarte en Vendalia.</p>
                <br />
                <h2 className='text-2xl'>5. Tu Contenido</h2>
                <br />
                <p>El contenido que publiques mediante la utilización de nuestros Servicios es tu contenido (por lo que lo denominaremos &quot;Tu Contenido&quot;). No hacemos ninguna reivindicación al respecto. Esto incluye todo lo que publiques mediante nuestros Servicios (como nombres de usuario, nombres de tienda, fotos del perfil, fotos de los anuncios, descripciones de los anuncios, opiniones, comentarios, vídeos, etc.).</p>
                <br />
                <p><strong>A. Responsabilidad de Tu Contenido.</strong> Entiendes que Tu Contenido es responsabilidad tuya únicamente. Declaras que tienes todos los derechos necesarios a todas las partes para publicar Tu Contenido y que no estás infringiendo ni violando los derechos de terceros mediante su publicación.</p>
                <br />
                <p><strong>B. Permiso para utilizar Tu Contenido.</strong> Al publicar Tu Contenido a través de nuestros Servicios, concedes a Vendalia y, tal como lo autorice Vendalia a su entera discreción, a terceros, licencia para usarlo. No pretendemos tener ningún derecho de propiedad sobre Tu Contenido, pero tenemos tu permiso para utilizarlo con el fin de ayudarnos a funcionar y crecer. De esa manera, no infringiremos cualesquiera derechos que tengas en Tu Contenido y podemos ayudarte a promocionarlo. Por ejemplo, aceptas que Vendalia podría ofreceros a ti o a los compradores de Vendalia promociones en el Sitio, de vez en cuando, que puedan guardar relación con tus anuncios u otros anuncios en Vendalia.</p>
                <br />
                <p><strong>C. Derechos que nos concedes.</strong> (Esta es la versión de jerga legal de la última sección.) Al publicar Tu Contenido, concedes a Vendalia y, tal como lo autorice Vendalia a su entera discreción, a terceros, una licencia no exclusiva, mundial, sin regalías, irrevocable, sublicenciable y perpetua para usar, mostrar, editar, modificar, reproducir, distribuir, almacenar y preparar trabajos derivados. Esto nos permite proporcionar los Servicios y promocionar Vendalia, tu tienda de Vendalia, otras tiendas y anuncios, o los Servicios en general, en cualquier formato y mediante cualquier canal, incluyendo todos los Servicios de Vendalia, nuestros socios o sitios web de terceros o medios publicitarios. Aceptas no reivindicar ningún derecho moral o de publicidad contra nosotros por usar Tu Contenido. También reconoces nuestro interés legítimo por usarlo, de conformidad con el ámbito de aplicación de esta licencia, en la medida en la que este contenga cualquier información personal.</p>
                <br />
                <p>Suena excesivo, pero es necesario para que podamos mantener el funcionamiento de la plataforma. Considera estos ejemplos: si cargas una foto o vídeo de un anuncio en tu tienda de Vendalia, tenemos permiso para mostrarlos a los compradores y podemos cambiar su tamaño o mejorar la calidad para que el comprador que utiliza la aplicación móvil pueda verlos bien; si publicas una descripción en inglés, podemos traducirla al francés para que un comprador en París pueda conocer la historia de tu artículo; y si publicas una bonita foto de tu collar hecho a mano más reciente, podemos destacarla (normalmente junto con el nombre de tu tienda y una foto) en nuestra página de inicio, en uno de nuestros blogs o incluso en un cartel para contribuir a la promoción de tu negocio y el nuestro.</p>
                <br />
                <p><strong>D. Notificación de contenido no autorizado.</strong> Respetamos enormemente los derechos de propiedad intelectual y nos comprometemos a seguir los procedimientos legales apropiados para eliminar el contenido que infrinja los Servicios. Si encontraras que se han publicado en los Servicios contenido de tu propiedad o sobre el que tienes derechos sin tu permiso y quieres que se retire, sigue los pasos que se indican en nuestra política de propiedad intelectual. Si se sospecha que Tu Contenido infringe la propiedad intelectual de otra persona, adoptaremos las medidas apropiadas, desde retirarlo si recibimos una notificación de infracción que cumpla con nuestras políticas hasta cancelar tu cuenta si descubrimos que eres un infractor reincidente. Te enviaremos una notificación si eso sucede.</p>
                <br />
                <h2 className='text-2xl'>6. Tu uso de nuestros Servicios</h2>
                <br />
                <p><strong>Licencia para usar nuestros Servicios.</strong> Te otorgamos una licencia limitada, no exclusiva, intransferible y revocable para usar nuestros Servicios, sujeta a las Condiciones y las siguientes restricciones en particular:</p>
                <br />
                <p><strong>A. No uses nuestros Servicios para infringir la ley.</strong> Aceptas que no infringirás ninguna ley en relación con tu uso de los Servicios. Esto incluye cualquier ley local, estatal, federal e internacional que pueda aplicarse a tu persona. Por ejemplo, es tu responsabilidad obtener los permisos o licencias que tu tienda requiera, y cumplir con los requisitos legales aplicables en las jurisdicciones correspondientes. Esto incluye la venta y la entrega de tus artículos, como la verificación de edad en el momento de la entrega donde se exija por ley. No podrás vender ningún objeto que infrinja cualquier ley; debes cumplir con nuestra política de sanciones y no puedes cometer fraude ni robo, adoptar conductas de competencia desleal o conductas amenazantes, ni cometer ningún otro acto ilegal o delito contra nosotros, contra otro usuario de Vendalia o contra un tercero.</p>
                <br />
                <p><strong>B. Paga tus facturas.</strong> Eres responsable de pagar todas las tarifas que debas a Vendalia. Excepto por lo establecido a continuación, también eres la única persona responsable de cobrar o pagar cualesquiera impuestos aplicables a las compras o ventas que realices a través de nuestros Servicios. Cuando corresponda, Vendalia calculará, recaudará y remitirá el impuesto sobre el valor añadido (IVA) y el impuesto sobre las ventas. Algunos países podrían hacer referencia al IVA con otros términos, como GST (impuesto sobre bienes y servicios), pero nos referiremos al IVA, al GST y a los impuestos sobre las ventas locales en conjunto como &quot;IVA&quot;. Consulta esta pregunta frecuente y nuestra política de tarifas y pagos para obtener más información sobre los impuestos, incluyendo detalles sobre cómo recauda y remite Vendalia los impuestos que pagan los vendedores. Tus tarifas, facturas, impuestos y cómo puedes pagarlos se explican detalladamente en nuestra política de tarifas y pagos.</p>
                <br />
                <p><strong>C. No robes nuestro material.</strong> Te comprometes a no rastrear, extraer o utilizar un programa araña en ninguna página de los Servicios y a no realizar ingeniería inversa o intentar obtener el código fuente de los Servicios (incluyendo tanto la Propiedad intelectual de Vendalia como el Contenido de Vendalia) sin nuestro permiso expreso. Si quieres usar nuestra API, sigue nuestras condiciones de uso de la API.</p>
                <br />
                <p><strong>D. No intentes dañar nuestros sistemas.</strong> Aceptas no interferir o intentar perturbar nuestros Servicios, por ejemplo, mediante la distribución de un virus, el envío excesivo de solicitudes a nuestro sitio o plataforma, o cualquier código informático dañino.</p>
                <br />
                <p><strong>E. Sigue nuestra política de marcas.</strong> El nombre &quot;Vendalia&quot; y el resto de nuestras marcas, frases, logotipos y diseños que utilizamos en nuestros Servicios (las Marcas Comerciales de Vendalia) son marcas comerciales, marcas de servicio o imágenes comerciales de Vendalia en EE. UU. y otros países. Si quieres usar nuestras marcas, aceptas seguir nuestra política de marcas comerciales.</p>
                <br />
                <p><strong>F. Comparte tus ideas.</strong> ¡Nos encantan tus sugerencias e ideas! Nos pueden ayudar a mejorar tu experiencia y nuestros Servicios. Todas las ideas u otros materiales que envíes a Vendalia (sin incluir Tu Contenido o los artículos que vendes a través de nuestros Servicios) se consideran no confidenciales y no propietarios para ti. Nos otorgas una licencia no exclusiva, mundial, libre de regalías, irrevocable, sublicenciable y perpetua para utilizar y publicar esas ideas y materiales para cualquier propósito, sin compensación para ti.</p>
                <br />
                <p><strong>G. Habla con nosotros en línea.</strong> De vez en cuando, te proporcionaremos cierta información legal por escrito. Al utilizar nuestros Servicios, aceptas nuestra política de comunicaciones electrónicas, en la que se describe cómo te facilitamos esa información. En ella, se explica que te podemos enviar información vía electrónica (por ejemplo, por correo electrónico) en lugar de enviarte por correo postal copias en papel (es mejor para el medio ambiente), y que tu contrato electrónico equivale a tu firma en el papel.</p>
                <br />
                <h2 className='text-2xl'>7. Rescisión</h2>
                <br />
                <p><strong>Rescisión por tu parte.</strong> No nos gusta que te vayas, pero puedes cancelar tu cuenta en cualquier momento desde la configuración de tu cuenta. Puedes encontrar más información en este <a href="#">artículo de la Ayuda</a>. Rescindir tu cuenta no afectará la disponibilidad de parte de Tu Contenido que enviaste a través de los Servicios antes de la rescisión. Ah, y todavía tendrás que pagar todas las facturas pendientes.</p>
                <br />
                <p><strong>Rescisión por nuestra parte.</strong> Podremos cerrar o suspender tu cuenta (y cualesquiera cuentas que Vendalia determine que guardan relación con tu cuenta) y rescindir tu acceso a los Servicios si tuviéramos motivos para creer que tú, Tu Contenido o cómo usas los Servicios violan nuestras Condiciones. Si así fuera, es importante entender que no tienes un derecho contractual o legal para seguir utilizando nuestros Servicios, por ejemplo, para vender o comprar en nuestros sitios web o nuestras aplicaciones móviles. En general, te mandaremos una notificación si decidimos cerrar o suspender tu cuenta, a menos que hayas infringido de manera recurrente nuestras Condiciones o que tengamos motivos legales o normativos que nos impidan hacerlo.</p>
                <br />
                <p>En el caso de rescindir tu cuenta, ya sea por tu parte o por la nuestra, puedes perder toda la información asociada a ella, incluido Tu Contenido.</p>
                <br />
                <p><strong>Podríamos interrumpir la prestación de los Servicios.</strong> Vendalia se reserva el derecho de modificar, suspender o interrumpir cualquiera de los Servicios para ti, cualquiera o todos los usuarios, en cualquier momento, por cualquier motivo, incluyendo los que se recogen en las políticas de Vendalia en consonancia con estas Condiciones de uso. No seremos responsables ante ti por el efecto que cualquier cambio en los Servicios pueda tener sobre ti, incluidos tus ingresos o tu capacidad de generar ingresos a través de los Servicios.</p>
                <br />
                <p><strong>Perduración de vigencia.</strong> Las Condiciones permanecerán en vigor incluso después de revocar tu acceso al Servicio, o después de que dejes de usar el Servicio.</p>
                <br />
                <h2 className='text-2xl'>8. Garantías y limitación de responsabilidad (o las cosas por las que no nos puedes demandar)</h2>
                <br />
                <p><strong>Artículos que compras.</strong> Entiendes que nosotros no fabricamos, almacenamos ni inspeccionamos ninguno de los artículos que se venden a través de nuestros Servicios. Nosotros proporcionamos el lugar; los artículos en nuestro mercado son producidos, publicados y vendidos directamente por vendedores independientes, por lo que Vendalia no puede emitir y no emite ninguna garantía sobre su calidad, seguridad, autenticidad o legalidad. Cualquier acción judicial relacionada con un artículo que compres debe ser presentada directamente contra el vendedor del artículo. Nos exoneras de cualquier reclamación relacionada con los artículos vendidos a través de nuestros Servicios, incluidos artículos defectuosos, tergiversaciones de los vendedores o artículos que hayan causado daños físicos (como las reclamaciones por responsabilidad del producto).</p>
                <br />
                <p><strong>Contenido al que accedes.</strong> Podrás encontrarte con materiales que te parezcan ofensivos o inadecuados durante el uso de nuestros Servicios. No hacemos ninguna reivindicación con respecto a ninguno de los contenidos publicados por los usuarios a través de los Servicios. No somos responsables de la exactitud, el cumplimiento de los derechos de autor, la legalidad o la decencia del contenido publicado por los usuarios a los que accedes a través de los Servicios. Nos eximes de toda responsabilidad relacionada con ese contenido.</p>
                <br />
                <p><strong>Personas con las que interactúas.</strong> Puedes utilizar los Servicios para interactuar con otras personas, ya sea por Internet o en persona. Sin embargo, entiendes que nosotros no evaluamos a los usuarios de nuestros Servicios más que para cumplir determinadas obligaciones de conformidad y legales, y nos eximes de toda responsabilidad relacionada con tus interacciones con otros usuarios. Ten cuidado y actúa con cautela y buen juicio en todas las interacciones con los demás, sobre todo si te vas a reunir con alguien en persona. En este <a href="#">artículo de la Ayuda</a> se incluyen algunos buenos consejos sobre cómo tratar las reuniones en persona.</p>
                <br />
                <p><strong>Servicios de terceros.</strong> Nuestros Servicios pueden contener enlaces a sitios web o servicios de terceros que nosotros no poseemos ni controlamos (por ejemplo, enlaces a Facebook, Twitter y Pinterest). También es posible que necesites usar el producto o servicio de un tercero con el fin de utilizar algunos de nuestros Servicios (como un dispositivo móvil compatible para utilizar nuestras aplicaciones móviles). Al acceder a estos servicios de terceros, lo haces bajo tu propio riesgo. Los terceros podrán requerirte que aceptes sus propias condiciones de uso. Nosotros no somos parte de esos acuerdos; son exclusivamente entre tú y el tercero.</p>
                <br />
                <p><strong>Tarjetas regalo y promociones.</strong> Aceptas que no ofrecemos garantías con respecto al saldo de tu tarjeta regalo y que no somos responsables del acceso no autorizado a su código, como tampoco de su posible alteración, robo o destrucción, que resulte de cualquier acción que emprendas tú o un tercero. También aceptas que podremos suspender o prohibir el uso de tu tarjeta regalo si informas del robo de esta o de su código, o si creemos que el saldo de la tarjeta regalo se está usando de manera sospechosa, fraudulenta o de cualquier otra manera no autorizada. Si el código de tu tarjeta regalo deja de funcionar, la única solución es que emitamos un reemplazo del código de la tarjeta regalo. Al participar en una oferta especial o promoción, aceptas que no podrás reclamar a posteriori que las reglas de esa oferta o promoción especial eran ambiguas.</p>
                <br />
                <div className='border p-4'>
                    <p><strong>GARANTÍAS.</strong> NUESTRO OBJETIVO ES HACER QUE NUESTROS SERVICIOS TENGAN LA MÁXIMA CALIDAD POSIBLE, PERO NO SOMOS PERFECTOS Y, A VECES, LAS COSAS PUEDEN FALLAR. ENTIENDES QUE NUESTROS SERVICIOS SE PROPORCIONAN &quot;TAL CUAL&quot; Y &quot;SEGÚN DISPONIBILIDAD&quot; SIN NINGÚN TIPO DE GARANTÍA (EXPRESA O IMPLÍCITA). RENUNCIAMOS EXPRESAMENTE A TODA GARANTÍA DE TITULARIDAD, NO INFRACCIÓN, COMERCIABILIDAD Y ADECUACIÓN PARA UN FIN DETERMINADO, ASÍ COMO A CUALQUIER GARANTÍA IMPLÍCITA DERIVADA DEL RENDIMIENTO, LA TRANSACCIÓN O EL USO COMERCIAL.</p>
                    <br />
                    <p>NO GARANTIZAMOS QUE: (I) LOS SERVICIOS SEAN SEGUROS O ESTÉN DISPONIBLES EN CUALQUIER MOMENTO O LUGAR DETERMINADO; (II) SE CORRIJAN LOS DEFECTOS O ERRORES; (III) LOS SERVICIOS ESTÉN LIBRES DE VIRUS U OTROS MATERIALES NOCIVOS; O (IV) LOS RESULTADOS DE LA UTILIZACIÓN DE LOS SERVICIOS CUMPLAN CON SUS EXPECTATIVAS. USAS LOS SERVICIOS BAJO TU PROPIO RIESGO. ALGUNAS JURISDICCIONES NO PERMITEN LIMITACIONES EN LAS GARANTÍAS IMPLÍCITAS, POR LO QUE ESTA LIMITACIÓN PUEDE NO CORRESPONDER EN TU CASO.</p>
                    <br />
                    <p><strong>LÍMITES DE RESPONSABILIDAD.</strong> EN LA MÁXIMA MEDIDA PERMITIDA POR LA LEY, NI VENDALIA NI SUS EJECUTIVOS, DIRECTORES, EMPLEADOS, AGENTES, SUBSIDIARIAS, SOCIOS O FILIALES SERÁN RESPONSABLES ANTE TI POR CUALQUIER PÉRDIDA DE BENEFICIOS O INGRESOS, NI DE LOS DAÑOS CONSECUENTES, INCIDENTALES, INDIRECTOS, ESPECIALES O PUNITIVOS QUE SURJAN DE O EN RELACIÓN CON LOS SERVICIOS O ESTAS CONDICIONES. EN NINGÚN CASO, LA RESPONSABILIDAD TOTAL DE VENDALIA POR CUALESQUIERA DAÑOS SUPERARÁ LA CANTIDAD DE: (A) 100 USD, (B) CUALESQUIERA IMPORTES ADEUDADOS BAJO EL PROGRAMA DE PROTECCIÓN DE COMPRAS DE VENDALIA HASTA EL PRECIO QUE PAGARAS POR UN ARTÍCULO VENDIDO POR UN TERCERO EN VENDALIA (INCLUIDO CUALQUIER IMPUESTO SOBRE LAS VENTAS APLICABLE) Y SUS GASTOS DE ENVÍO ORIGINALES, O (C) LA CANTIDAD QUE PAGARAS A VENDALIA EN TARIFAS EN LOS ÚLTIMOS 12 MESES PREVIOS A CUALQUIER ACCIÓN QUE DIERA LUGAR A LA RESPONSABILIDAD. ALGUNAS JURISDICCIONES NO PERMITEN LIMITACIONES EN LOS DAÑOS ACCIDENTALES O EMERGENTES, ASÍ QUE ES POSIBLE QUE LAS LIMITACIONES ANTERIORES NO CORRESPONDER EN TU CASO.</p>
                </div>
                <br />
                <h2 className='text-2xl'>9. Indemnización (y qué sucede si haces que nos demanden)</h2>
                <br />
                <p>Esperamos que esto no suceda nunca, pero si Vendalia es demandada o recibe un aviso o una demanda en los tribunales o arbitral por acción (o por omisión) tuya, aceptas defendernos e indemnizarnos. Esto significa, sin limitación, que defenderás, reembolsarás, compensarás y eximirás a Vendalia (incluidos todos nuestros empleados, ejecutivos, directores, agentes, subsidiarias y afiliados) de toda acusación, reclamación, demanda, litigio, pérdida, responsabilidad o gasto de cualquier tipo (incluidas las costas razonables de los abogados) que surjan de tus acciones, el uso (o mal uso) que hagas de nuestros Servicios, el incumplimiento por tu parte de las Condiciones, artículos que compres o vendas a través de los Servicios, o tu infracción real o supuesta de cualquier ley o derechos de terceros. Nos reservamos el derecho de gestionar nuestra defensa legal de la manera que nos parezca, incluso si nos estás indemnizando, en cuyo caso te comprometes a cooperar con nosotros para que podamos llevar a cabo nuestra estrategia.</p>
                <br />
                <h2 className='text-2xl'>10. Disputas con otros usuarios</h2>
                <br />
                <p>Si te encuentras en una controversia con otro usuario de los Servicios de Vendalia o con un tercero, te animamos a ponerte en contacto con la otra parte y tratar de resolverla de forma amistosa.</p>
                <br />
                <p><strong>Sistema de gestión de casos.</strong> Los compradores y vendedores que sean incapaces de resolver una disputa relacionada con una transacción en nuestros sitios web o aplicaciones móviles podrán participar en nuestro sistema de casos con una cuenta registrada. Puedes encontrar más información sobre el sistema de gestión de casos en este artículo de la Ayuda. A nuestra entera discreción, Vendalia intentará ayudarte a resolver disputas de buena fe, pero no emitiremos juicios ni determinaciones con respecto a cuestiones o reclamaciones legales. Vendalia no tiene la obligación de resolver, o de ayudar a resolver, ninguna disputa.</p>
                <br />
                <p><strong>Exoneración de Vendalia.</strong> Exoneras a Vendalia de cualesquiera demandas arbitrales o en los tribunales y daños que surjan de controversias con otros usuarios o terceros.</p>
                <br />
                <h2 className='text-2xl'>11. Acuerdo de arbitraje y renuncia a acciones colectivas</h2>
                <br />
                <p>Si tienes un problema con nosotros, infórmanos y trabajaremos juntos de buena fe para resolverlo. Si no pudiéramos solucionarlo, tú y Vendalia (incluyendo nuestros empleados, directivos, directores, agentes, subsidiarias y filiales) aceptáis remitir la disputa exclusivamente a arbitraje individual vinculante, y no os demandaréis mutuamente en los tribunales frente a un juez o un jurado, excepto en las circunstancias limitadas descritas a continuación.</p>
                <br />
                <p>Esta sección 11 (a la que también nos referiremos como &quot;Acuerdo de arbitraje&quot; o &quot;Acuerdo&quot;) se te aplica solo si vives en América del Norte o del Sur, y hasta el máximo permitido por la ley.</p>
                <br />
                <p>Lee esta sección detenidamente, ya que afecta a tus derechos.</p>
                <br />
                <p><strong>A. Disputas que arbitraremos.</strong> Tú y Vendalia aceptáis someteros a arbitraje individual obligatorio para todas las reclamaciones que surjan de o en relación con los Servicios, con la versión actual y con versiones anteriores de las Condiciones, con cualesquiera productos, datos o contenido comprado, vendido, ofrecido, mostrado, transmitido, publicado o al que se haya accedido a través de los Servicios, y con acciones o declaraciones hechas por Vendalia o sus usuarios, en cada caso incluyendo las disputas que surgieran antes de la fecha de entrada en vigor de las presentes Condiciones (cada una, una &quot;Disputa&quot;). La excepción es que cada una de las partes podrá (1) llevar demandas individuales aptas a proceso monitorio siempre y cuando estas no se escalen; y (2) solicitar medidas cautelares en los tribunales por infracción o uso indebido de derechos de propiedad intelectual (como marcas comerciales, derechos de autor y patentes). El resto de Disputas deberá someterse a arbitraje, lo que significa que tú y Vendalia renunciáis al derecho de denunciar ante los tribunales y a iniciar un proceso judicial con juez o con jurado.</p>
                <br />
                <p><strong>B. Renuncia a acciones colectivas y representativas.</strong> Tú y Vendalia aceptáis que cada una de las partes puede presentar una demanda contra la otra parte únicamente de manera individual, y no con acciones de demanda colectivas, representativas o grupales (y cada parte renuncia a cualquier derecho que tenga a presentar dichas demandas). Cada parte podrá solicitar u obtener únicamente asistencia individual, y, con la excepción de lo dispuesto en la sección 11.F (Arbitraje grupal), las disputas entre las partes no pueden arbitrarse ni consolidarse con las de ninguna otra persona o entidad. Si un tribunal (después de agotar todos los recursos) decide que alguna parte de esta sección 11.B no es aplicable a una demanda o solicitud de medidas en concreto (como una solicitud de medidas cautelares públicas), únicamente dicha demanda o solicitud de medidas en particular deberá separarse del procedimiento de arbitraje y podrá litigarse en los tribunales (pero únicamente después de que el arbitrador dicte una resolución sobre las alegaciones y las soluciones arbitrables).</p>
                <br />
                <p><strong>C. Resolución de disputas extraoficial.</strong> Antes de presentar un arbitraje, tú y Vendalia intentaréis de buena fe solucionar cualquier disputa extraoficialmente. Para iniciar el proceso de disputa, debes enviar un aviso individualizado por escrito (&quot;Aviso de disputa&quot;) a disputeresolution@vendalia.com que incluya (1) tu nombre, número de teléfono, nombre de usuario y nombre de la tienda (si corresponde), y dirección de correo de tu cuenta, y (2) una descripción de la Disputa y cómo te gustaría resolverla. Si Vendalia tiene una Disputa contigo, te enviaremos un Aviso de disputa con la misma información a la dirección de correo electrónico que hay registrada en tu cuenta. Cuando se ha recibido un Aviso de disputa completo, el destinatario tiene 60 días para investigar las denuncias. Si alguna de las partes solicita una conferencia de acuerdos durante este periodo, tú y Vendalia deberéis cooperar para programar dicha reunión por teléfono o videoconferencia. Tú y Vendalia participaréis personalmente y podréis llevar cada uno vuestro abogado, pero la conferencia debe ser individualizada, aunque la(s) misma(s) firma(s) represente(n) a varias partes. Para las demandas que figuren en el Aviso de disputa, cualquier prescripción se suspenderá desde la fecha en la que se reciba el aviso (i) hasta el último de los 60 días, o (ii) después de que se complete una conferencia de acuerdos solicitada de manera oportuna (&quot;Periodo de resolución extraoficial&quot;). No se puede presentar un arbitraje hasta que haya terminado el Periodo de resolución extraoficial, y un tribunal puede ordenar la presentación o el procesamiento de un arbitraje contraviniendo lo dispuesto en esta sección.</p>
                <br />
                <p><strong>D. Reglas y procedimientos de arbitraje.</strong> Para iniciar el arbitraje, una de las partes (tú o nosotros) debe presentar una demanda arbitral ante la American Arbitration Association (&quot;AAA&quot;). Puedes enviar a Vendalia cualquier demanda arbitral por correo postal a: Vendalia, Inc. c/o The Corporation Trust Company, 1209 Orange Street, Wilmington, DE 19801, EE. UU. Si Vendalia tiene una Disputa contigo, te enviaremos una demanda arbitral a la dirección de correo electrónico que hay registrada en tu cuenta. Si la AAA no puede o no va a administrar el arbitraje de conformidad con la sección 11, tú y nosotros seleccionaremos otro proveedor (y si no llegamos a un acuerdo, será un tribunal quien decida el proveedor).</p>
                <br />
                <p>El arbitraje se realizará en inglés y con un único arbitrador. La audiencia del arbitraje (si lo hubiera) se celebrará por videoconferencia, a menos que cualquiera de las partes solicite una audiencia en persona y el arbitrador acepte. Si se requiere una audiencia en persona, se celebrará en el condado en el que resides (para residentes de EE. UU.), en la ciudad de Nueva York en el condado de Nueva York (para residentes de fuera de EE. UU.) o tal como lo determine el arbitrador (en el caso de un Arbitraje grupal).</p>
                <br />
                <p>El arbitraje se decidirá según las normas de arbitraje del consumidor de la AAA, en su forma enmendada en este Contrato. No obstante, si usas los Servicios como empresa y tus demandas o las demandas de Vendalia superan los 75 000 USD, se aplicarán las normas de arbitraje comercial de la AAA, en su forma enmendada en este Acuerdo. Al igual que en los tribunales, el arbitrador aplicará la ley en vigor, cualquier abogado debe cumplir con las reglas federales de procedimiento civil 11(b) y el arbitrador puede imponer cualesquiera sanciones previstas en la regla 11 de las normas de la AAA o en otra legislación aplicable. El arbitrador también deberá aplicar las leyes relativas a limitaciones y otras defensas basadas en el tiempo, ofertas de sentencia/compromiso y normas de condena del pago de las costas del mismo modo que lo haría un tribunal.</p>
                <br />
                <p>El arbitrador tendrá autoridad exclusiva para resolver todos los problemas, excepto si un tribunal tiene autoridad exclusiva para decidir cuestiones relativas a la arbitrabilidad de una disputa, la aplicabilidad de cualquier parte de esta sección 11 (Acuerdo de arbitraje y resolución de disputas) y el cumplimiento de cualquier parte con la sección 11.C (Resolución de disputas extraoficial). Con excepción de lo dispuesto en la sección 11.F (Arbitraje grupal), el arbitrador puede reconocer daños y otras indemnizaciones únicamente en favor del demandante individual, y únicamente hasta el extremo necesario para aplicar las sanciones garantizadas por las demandas individuales del demandante. El arbitrador no estará obligado a seguir las decisiones adoptadas en otros arbitrajes. La sanción del arbitrador es final y vinculante sobre ti y sobre Vendalia. El fallo sobre la sanción se dictará en cualquier tribunal con jurisdicción.</p>
                <br />
                <p><strong>E. Gastos de arbitraje.</strong> El pago de todas las tasas judiciales y administrativas, así como de los gastos derivados de la gestión del caso, la audiencia y los relativos al arbitrador (&quot;Costas de arbitraje&quot;), estará regido por las normas de la AAA y la lista de honorarios, salvo que se especifique lo contrario en el presente Acuerdo de arbitraje. Si eres el consumidor y tu parte de las Costas de arbitraje es superior a lo que pagarías en los tribunales de cualquier otro modo, infórmanos y Vendalia pagará la diferencia en tu nombre.</p>
                <br />
                <p><strong>F. Arbitraje grupal.</strong> Para garantizar una resolución eficiente, si en un periodo de 90 días, 25 o más demandantes envían Avisos de disputa o presentan solicitudes de arbitraje con demandas similares (por ejemplo, con hechos o acontecimientos y problemas legales iguales o similares) y están representados por el mismo abogado o por abogados coordinados, las disputas deberán arbitrarse en grupos de hasta 50 demandantes cada uno (&quot;Grupo&quot;). En concreto, tras la notificación de cada parte, la AAA deberá agrupar a los demandantes en: (1) un solo Grupo (si hay entre 25 y 50 demandantes) o (2) Grupos de 50 demandantes cada uno, con un último Grupo más pequeño compuesto por el resto de los demandantes (si hay más de 50 demandantes). Por tanto, la AAA deberá aportar un único arbitrador designado por la AAA para la resolución de cada Grupo como un único arbitraje consolidado, un conjunto de Costas de arbitraje y una audiencia (si la hubiera) por Grupo, celebrada por videoconferencia (o en un lugar decidido por el arbitrador). Las partes cooperarán de buena fe para poner en marcha este proceso y minimizar el tiempo y los costes de arbitraje. Cualesquiera dificultades con respecto a las determinaciones administrativas por parte de la AAA serán asistidas por un arbitrador en un único proceso. Si esta sección 11.F resultara inaplicable para un demandante o Grupo en particular, se separará para dicho demandante o Grupo, y dichas partes deberán arbitrar en procedimientos individuales.</p>
                <br />
                <p><strong>G. Renuncia.</strong> Tienes un derecho limitado a renunciar a este Acuerdo de arbitraje (salvo la sección 11.I). En concreto, si eres usuario nuevo de nuestros Servicios, puedes renunciar a este Acuerdo de arbitraje en un plazo de 30 días después de aceptar previamente las Condiciones. Si ya eres usuario de nuestros Servicios, puedes renunciar en un plazo de 30 días a partir de la fecha de entrada en vigor (indicada arriba). Para expresar tu renuncia, debes enviar en el plazo debido un correo electrónico a arbitrationoptout@vendalia.com con tu nombre, dirección de correo electrónico de tu cuenta, nombre de usuario y nombre de tu tienda (si corresponde), y una solicitud de renuncia al arbitraje. Si tu renuncia se tramita correctamente, ni Vendalia ni tú tendréis la obligación de arbitrar una disputa como resultado del presente (o de cualquier versión anterior del) Acuerdo de arbitraje, pero las Condiciones (y cualesquiera otros acuerdos entre nosotros) se te seguirán aplicando. Si actualizamos las Condiciones después de que tu renuncia se haya tramitado correctamente, seguiremos respetando tu renuncia, pero dichas actualizaciones no supondrán una nueva oportunidad de renuncia al arbitraje.</p>
                <br />
                <p><strong>H. Cambios futuros en el Acuerdo de arbitraje.</strong> Vendalia te notificará los cambios materiales en el presente Acuerdo de arbitraje con al menos 30 días de antelación a su entrada en vigor. Podrás rechazar los cambios futuros en el Acuerdo de arbitraje enviando un correo electrónico a arbitrationchanges@vendalia.com en un plazo de 30 días después de recibir el aviso. Deberás incluir tu nombre, tu dirección de correo electrónico asociada con tu cuenta y tu cuenta o tus cuentas de Vendalia. De lo contrario, quedarás sujeto al cambio y el Acuerdo de arbitraje modificado se aplicará a todas las Disputas que haya entre tú y Vendalia, incluyendo las que surgieran antes de la fecha de entrada en vigor de los cambios, pero con exclusión de cualesquiera demandas pendientes en arbitraje (o en los tribunales, si se permite) a fecha de la entrada en vigor. Si rechazas un cambio, quedarás sujeto a la versión más reciente del Acuerdo de arbitraje previo al cambio rechazado.</p>
                <br />
                <p><strong>I. Elección de ley y foro.</strong> Vendalia tiene su sede en Nueva York. Por tanto, si hubiera demandas entre tú y Vendalia que no estén sujetas a arbitraje, tú y Vendalia aceptáis cada uno litigar dichas demandas exclusivamente en el estado o en los tribunales federales del condado de Nueva York (Nueva York), y remitiros a la jurisdicción personal de dichos tribunales. Se aplica una excepción en el caso de presentar un proceso monitorio, que puede hacerse en el condado en el que resides. Salvo como lo prohíba la ley, estas Condiciones, y todas las disputas que haya entre nosotros, se regirán exclusivamente por la ley de Nueva York, con independencia de las reglas de conflicto de leyes, y la ley federal de EE. UU. (incluida la Ley federal de arbitraje). Por claridad, esta sección 11.I seguirá en vigor aunque renuncies correctamente al arbitraje según lo dispuesto en la sección 11.G.</p>
                <br />
                <h2 className='text-2xl'>12. Resolución de disputas (resto del mundo)</h2>
                <br />
                <p>Esta sección 12 se aplica si tu país de establecimiento o residencia principal está en Europa (incluidos el Espacio Económico Europeo, Suiza y Reino Unido), Asia, Australia o África. Como tu contrato es con Vendalia Ireland UC, cada uno de nosotros acepta que las Condiciones y cualesquiera disputas que haya entre nosotros se regirán exclusivamente por la ley de Irlanda, y que se dirimirán exclusivamente en los tribunales de Irlanda, excepto hasta donde lo prohíba la ley. Si eres un consumidor individual, podrías tener el derecho de apelar a las leyes de protección al consumidor obligatorias de tu país de residencia o de llevar los procedimientos judiciales a los tribunales de ese país. Si Vendalia necesita hacer valer sus derechos sobre ti como consumidor individual, solo lo haremos en tu país de residencia. Queda excluida la aplicación de la Convención de las Naciones Unidas sobre los Contratos de Compraventa Internacional de Mercadería.</p>
                <br />
                <p>Si surge una disputa entre Vendalia y tú, te recomendamos que contactes con el equipo de asistencia de Vendalia para buscar una solución o que sigas el proceso de resolución de disputas extraoficial que se explica en la sección 11.C. Para vendedores de la UE, se puede consultar información sobre el Reglamento P2B entre plataformas y empresas en esta página, y plantear una cuestión relativa al P2B en este enlace. Además, tú o Vendalia podréis derivar las disputas que cumplan los requisitos a mediación ante el Centro para la Resolución Efectiva de Disputas o para resolverlas a través de la plataforma para la resolución de litigios en línea de la Comisión Europea.</p>
                <br />
                <h2 className='text-2xl'>13. Cambios en las condiciones</h2>
                <br />
                <p>Podremos actualizar estas Condiciones de cuando en cuando, también añadiendo condiciones completamente nuevas y eliminando condiciones existentes. Si los cambios son importantes, te informaremos con antelación publicándolos a través de los Servicios o enviándote un correo electrónico o mensaje sobre los cambios. Seguir usando los Servicios después de la fecha de entrada en vigor de los cambios supone la aceptación de las Condiciones actualizadas. Si no estás de acuerdo con los cambios, puedes cerrar tu cuenta.</p>
                <br />
                <h2 className='text-2xl'>14. Algunos puntos legales más matizados</h2>
                <br />
                <p>Las Condiciones, incluidas todas las políticas que constituyen las Condiciones, sustituyen cualquier otro acuerdo entre tú y Vendalia con respecto a los Servicios. Salvo por lo provisto en la sección 11, si alguna parte de las Condiciones resulta no ser válida o aplicable, esa parte se limitará en la medida mínima necesaria y se separará para que las Condiciones permanezcan en pleno vigor y efecto. Nuestra incapacidad de hacer cumplir cualquier parte de las Condiciones no es una renuncia a nuestro derecho de hacer cumplir posteriormente esa o cualquier otra parte de las Condiciones. Podremos ceder cualquiera de nuestros derechos y obligaciones sujetas a las Condiciones.</p>
                <br />
                <h2 className='text-2xl'>15. Información de contacto</h2>
                <br />
                <p>Si tienes alguna pregunta acerca de las Condiciones, envíanos un correo electrónico a: <a href="mailto:legal@vendalia.com">legal@vendalia.com</a>.</p>
                <br />
                <p>Estaremos encantados de facilitarte esta política en el idioma de tu preferencia, pero es importante que entiendas que tu uso de los servicios de Vendalia se regirá siempre por la versión en inglés. Puedes cambiar tus preferencias de idioma en la configuración de tu cuenta.</p>

            </div>
        </PublicPageContainer>

    )
}
