name: Deploy Next.js to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Adjust the Node.js version as needed

      - name: Install dependencies
        run: npm ci # Use 'npm ci' for faster and more reliable dependency installation

      - name: Build Next.js project
        run: npm run build

      - name: Check if .next directory exists
        run: |
          if [ -d "$GITHUB_WORKSPACE/.next" ]; then
            echo $GITHUB_WORKSPACE
          else
            echo ".next directory does not exist"
            exit 1
          fi
      - name: Check .next directory contents
        run: ls -la $GITHUB_WORKSPACE/.next
      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_SECRET }}
          script: |
            cd /var/www/html/
            pm2 stop all
            sudo git clone https://github.com/yagomateos/marketplace.git
            cd marketplace
            sudo npm install
            sudo rsync -av --remove-source-files /marketplace/ ../
            pm2 start npm --name "next-app" -- start
            pm2 save
            

